### ISSUE TITLE
Request Instructions on How to Reduce Constant Left Roll Tendency 

### ISSUE THREAD

**Issue by jayeye2011** [krzysk1/wilga#9]
@krzysk1 Hey, I get that you intentionally wanted the Wilga to always roll to the left. But can you tell me what I would need to change in the TMD file to reduce this or completely eliminate this characteristic? I have tried some things but could get nothing to work. The odd part is that not only does the plane start to roll to the left once it is airborne on takeoff (100% throttle) but even when you back off to 0% throttle it still wants to roll to the left. It's not something that can be taken out with right rudder either, you need to push the stick right aileron all the time regardless of throttle setting. My controller is calibrated and this is the only aircraft that does this to an extreme level.

**Comment by krzysk1** [comment]
I found that AspectRatioMultiplier was 4.0  instead of 2.0 on one wing. I fixed it and please check if it works.

Generally rolling is caused by the effect of the propeller on the wing and can be modified by the PropwashPercentage or PropwashRotation

BTW Do you know wiki pages?
https://www.aerofly.com/dokuwiki/doku.php/aircraft:tmd
https://www.aerofly.com/dokuwiki/doku.php/aircraft:tmd:airfoil
https://www.aerofly.com/dokuwiki/doku.php/aircraft:tmd:propeller
https://www.aerofly.com/dokuwiki/doku.php/aircraft:tmd:aerowing

There are a lot of useful information

**Comment by jayeye2011** [comment]
@krzysk1 The correction of the AspectRatioMultiplier did reduce the left roll tendency but did not eliminate it and applying right rudder still does not counter it as it still requires application of right aileron stick force. Aileron trim is sufficient to neutralize this though. But I would still like to know how to completely balance out the roll so I can fly with wings level with out having to apply right aileron stick force. As far as I can tell, unlike in X-Plane 11, there is no trim tab adjustment settings for any of the control surfaces in Aerofly FS. 

> BTW Do you know wiki pages? 

Yes, I have looked at these a lot trying to figure out your Wilga and Optica TMD files. However there parameters shown in the Wiki that are not in your TMD files and vice versa, parameters in your TMD files that are not in the Wiki. And there are parameters in the Wiki that have no text description like BetaSlope and BetaMax as far as I can tell. Also, I still don't know for sure if the Wiki is for Aerofly FS 2 or if it updated for FS 4 because there is only one Wiki I only see Aerofly FS 2 referenced.
"Aircraft Definition File (TMD-File)
The single [text-file](https://www.aerofly.com/dokuwiki/doku.php/simulator:text_files) with the file extension .tmd defines an Aerofly FS 2 aircraft's physics characteristics, visuals/animations and sound definition. This file is located in the [aircraft folder](https://www.aerofly.com/dokuwiki/doku.php/sdk:aircraft:introduction#aircraft_folder) together with other files like the aircraft description file [TMC](https://www.aerofly.com/dokuwiki/doku.php/aircraft:tmc)."

Please be assured that this is not a bug report, just a friendly request for advice on how to take something out, that while perfectly expectable for a simulation of a real life plane, is just a bit annoying for a casual flight simmer using a Logitech F710 game controller rather than flight yoke and rudder pedals setup.

**Comment by jayeye2011** [comment]
@krzysk1 Tried PropWashPercentage of 0.0 and PropWashRotation of 0.0 on all aerowing components (wings, horizontal and vertical stabilizers, and gear struts) and still could not zero out the right roll. Not sure about PropWashOmega, even after reading Wiki not sure what it is or if it causes this roll tendency, but setting it to 0.0 was bad so I tried 0.01 but that did not do anything for the roll tendency although it did cause full right rudder to actually have a slight impact on roll in addition to yaw  .

**Comment by jayeye2011** [comment]
@krzysk1 All right, I did it! I was able to zero out the roll tendency to my satisfaction using PropWashPercentage and PropWashRotation. I had to raise PropWashPercentage up a little but once that was done PropWashRotation actually then had an impact. So thanks for the assist.
